# Generated by Django 6.0.2 on 2026-03-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_sponsor_phone_sponsor_sponsorship_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsorship_tier',
            field=models.CharField(blank=True, choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('Partnership', 'Partnership')], max_length=50, null=True),
        ),
    ]
